### ISSUE TITLE
unable to run a local webapp

### ISSUE THREAD

**Issue by crsl4** [solislemuslab/bioklustering#12]
I follow the instructions in the readme file, and I get this error. I wonder if it has to do with me using python3.9.
```
$ cd BioKlustering-Website
$ python3 -m venv virtual-env
$ source virtual-env/bin/activate
$ pip3 install -r requirements.txt
Collecting numpy~=1.22
  Using cached numpy-1.23.3-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
Collecting pandas~=1.1.5
  Using cached pandas-1.1.5-cp39-cp39-macosx_10_9_x86_64.whl (10.3 MB)
Collecting bio~=1.3.2
  Using cached bio-1.3.9-py3-none-any.whl (270 kB)
Collecting scikit-learn~=0.23.2
  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-standalone-pip-1t19m7_t/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1'
       cwd: None
  Complete output (130 lines):
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation == "CPython"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX" and platform_python_implementation != "CPython"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting setuptools
    Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting Cython>=0.28.5
    Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting scipy>=0.19.1
    Using cached scipy-1.9.1-cp39-cp39-macosx_12_0_universal2.macosx_10_9_x86_64.whl (58.4 MB)
    Using cached scipy-1.9.0-cp39-cp39-macosx_12_0_universal2.macosx_10_9_x86_64.whl (58.4 MB)
    Using cached scipy-1.8.1-cp39-cp39-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.6 MB)
  Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
  Installing collected packages: numpy, wheel, setuptools, scipy, Cython
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-record-xhzkj65d/install-record.txt --single-version-externally-managed --prefix /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay --compile --install-headers /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay/include/site/python3.9/numpy
           cwd: /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/
      Complete output (98 lines):
      Running from numpy source directory.
  
      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:
  
        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)
  
  
      /bin/sh: svnversion: command not found
      non-existing path in 'numpy/distutils': 'site.cfg'
      /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running config_cc
      running config_fc
      running build_src
      creating build
      creating build/src.macosx-11-x86_64-3.9
      creating build/src.macosx-11-x86_64-3.9/numpy
      creating build/src.macosx-11-x86_64-3.9/numpy/distutils
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py", line 443, in <module>
          setup_package()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py", line 435, in setup_package
          setup(**metadata)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/core.py", line 171, in setup
          return old_setup(**new_attr)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/install.py", line 62, in run
          r = self.setuptools_run()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/install.py", line 36, in setuptools_run
          return distutils_install.run(self)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 664, in run
          self.run_command('build')
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/build.py", line 47, in run
          old_build.run(self)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/build_src.py", line 142, in run
          self.build_sources()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/build_src.py", line 153, in build_sources
          self.build_library_sources(*libname_info)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/build_src.py", line 286, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/build_src.py", line 369, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 667, in get_mathlib_info
          st = config_cmd.try_link('int main(void) { return 0;}')
        File "/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/lib/python3.9/site-packages/setuptools/_distutils/command/config.py", line 241, in try_link
          self._check_compiler()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/command/config.py", line 82, in _check_compiler
          self.fcompiler = new_fcompiler(compiler=self.fcompiler,
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/__init__.py", line 884, in new_fcompiler
          compiler = get_default_fcompiler(plat, requiref90=requiref90,
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/__init__.py", line 855, in get_default_fcompiler
          compiler_type =  _find_existing_fcompiler(matching_compiler_types,
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/__init__.py", line 806, in _find_existing_fcompiler
          c.customize(dist)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/__init__.py", line 530, in customize
          linker_so_flags = self.flag_vars.linker_so
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
          return self._get_var(name, conf_desc)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
          var = self._hook_handler(name, hook)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook
          return hook()
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/gnu.py", line 353, in get_flags_linker_so
          flags = GnuFCompiler.get_flags_linker_so(self)
        File "/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/numpy/distutils/fcompiler/gnu.py", line 144, in get_flags_linker_so
          os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
        File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
          value = self.encodevalue(value)
        File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
          raise TypeError("str expected, not %s" % type(value).__name__)
      TypeError: str expected, not int
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py'"'"'; __file__='"'"'/private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-install-_2q3j_vh/numpy_b3608c106e544eb6a7981a58cf9b8179/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-record-xhzkj65d/install-record.txt --single-version-externally-managed --prefix /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay --compile --install-headers /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay/include/site/python3.9/numpy Check the logs for full command output.
  WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
  You should consider upgrading via the '/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 -m pip install --upgrade pip' command.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/aa/f6/75297be19f48b7a8c2577753a3a700f98fc4db49d0e5ed3820dd8dee43d4/scikit-learn-0.23.2.tar.gz#sha256=20766f515e6cd6f954554387dfae705d93c7b544ec0e6c6a5d8e006f6f7ef480 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-standalone-pip-1t19m7_t/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/b7/wstc_mqx3gv_kb_dpqbxjvvh0000gq/T/pip-build-env-eo0gubos/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scikit-learn~=0.23.2 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.1.0rc1, 1.1.0, 1.1.1, 1.1.2)
ERROR: No matching distribution found for scikit-learn~=0.23.2
WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/Clauberry/Desktop/bioklustering/BioKlustering-Website/virtual-env/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by crsl4** [comment]
Ah! The first error message has the `python_version=='"'"'3.6'"'"'` part, so maybe it is python3.9 that's causing an issue.

**Comment by crsl4** [comment]
Fixed by changing the requirements in [this commit](https://github.com/solislemuslab/bioklustering/commit/c1ed00b0c539a058a656c1a75688156f2f2d34f8)
